networks:
    ipvlan:
        driver: ipvlan
        driver_opts:
            parent: wlp3s0 
        ipam:
            driver: default
            config:
            - subnet: 192.168.1.0/24
              gateway: 192.168.1.1
              ip_range: 192.168.1.128/25
